// themeConfig.js
const theme = {
  token: {
    colorPrimary: '#6f2c91',
    colorPrimaryHover: '#7a3caa',
    colorPrimaryActive: '#5b1f7a',
    colorLink: '#6f2c91',
    colorLinkHover: '#7a3caa',
    colorText: '#1a1a1a',
    colorTextSecondary: '#555555',
    colorTextPlaceholder: '#a0a0a0',
    colorBgBase: '#ffffff',
    colorBgContainer: '#fafafa',
    colorBgLayout: '#f5f5f5',
    colorBorder: '#d9d9d9',
    colorBorderSecondary: '#bfa6d6',
    colorError: '#ff4d4f',
    colorSuccess: '#52c41a',
    colorWarning: '#faad14',
    colorInfo: '#1890ff',
    fontSizeBase: '14px',
    fontSizeHeading1: '32px',
    fontSizeHeading2: '28px',
    fontSizeHeading3: '24px',
    fontSizeHeading4: '20px',
    fontSizeHeading5: '16px',
    fontSizeHeading6: '14px',
    lineHeightBase: '1.5',
    lineHeightHeading: '1.2',
    fontWeightNormal: '400',
    fontWeightBold: '700',
    borderRadiusBase: '4px',
    borderRadiusSm: '2px',
    borderRadiusLg: '6px',
    controlHeight: '32px',
    controlHeightLG: '40px',
    controlHeightSM: '24px',
  },
  components: {
    Button: {
      colorPrimary: '#6f2c91',
      colorPrimaryHover: '#7a3caa',
      colorPrimaryActive: '#5b1f7a',
      algorithm: true,
    },
    Input: {
      colorPrimary: '#6f2c91',
      colorBorder: '#d9d9d9',
      hoverBorderColor: '#6f2c91',
      borderRadius: 6,
      colorText: '#1a1a1a',
      placeholderColor: '#a0a0a0',
      bgColor: '#ffffff',
    },
    Card: {
      colorBgContainer: '#ffffff',
      borderRadius: 8,
      boxShadow: '0 1px 6px rgba(0,0,0,0.1)',
    },
    Table: {
      headerBg: '#fafafa',
      headerColor: '#1a1a1a',
      rowHoverBg: '#f0f7ff',
    },
    Menu: {
      itemHoverBg: '#f0f7ff',
      itemSelectedBg: '#e6f0ff',
      itemSelectedColor: '#6f2c91',
    },
  },
};

export default theme;
